[env:waveshare_esp32s3_185c]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38/platform-espressif32.zip
board = esp32-s3-devkitc1-n16r8
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_build.flash_size = 16MB
board_build.psram = enabled
board_build.arduino.memory_type = qio_opi

lib_deps =
  moononournation/GFX Library for Arduino@1.6.5

build_flags =
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCORE_DEBUG_LEVEL=0